### ISSUE TITLE
AttributeError: 'EventLoop' object has no attribute '_selector'

### ISSUE THREAD

**Issue by generalov** [saghul/aiouv#14]
I try to use `aiohttp` with `aiouv` but get many "Logging error" messages like this when PYTHONASYNCIODEBUG is enabled:

```
DEBUG:asyncio:Get address info api.github.com:443, family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>
DEBUG:asyncio:Getting address info api.github.com:443, family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1> took 87.464 ms: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.30.252.127', 443))]
DEBUG:asyncio:connect <socket.socket fd=9, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 0)> to ('192.30.252.127', 443)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 537, in __repr__
    polling = _test_selector_event(self._loop._selector,
AttributeError: 'EventLoop' object has no attribute '_selector'
Call stack:
  File "a.py", line 27, in <module>
    content = loop.run_until_complete(task)
  File "/tmp/python/lib/python3.5/site-packages/aiouv/_events.py", line 80, in run_until_complete
    self.run_forever()
  File "/tmp/python/lib/python3.5/site-packages/aiouv/_events.py", line 71, in run_forever
    self._run(pyuv.UV_RUN_DEFAULT)
  File "/tmp/python/lib/python3.5/site-packages/aiouv/_events.py", line 458, in _run
    r = self._loop.run(mode)
  File "/tmp/python/lib/python3.5/site-packages/aiouv/_events.py", line 541, in _process_ready
    handler._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 293, in _wakeup
    self._step(value, None)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "a.py", line 18, in fetch
    response = await aiohttp.get(url, loop=loop)
  File "/tmp/python/lib/python3.5/site-packages/aiohttp/client.py", line 474, in get
    ret = yield from request(hdrs.METH_GET, url, **kwargs)
  File "/tmp/python/lib/python3.5/site-packages/aiohttp/client.py", line 466, in request
    read_until_eof=read_until_eof)
  File "/tmp/python/lib/python3.5/site-packages/aiohttp/client.py", line 131, in request
    conn = yield from self._connector.connect(req)
  File "/tmp/python/lib/python3.5/site-packages/aiohttp/connector.py", line 292, in connect
    transport, proto = yield from self._create_connection(req)
  File "/tmp/python/lib/python3.5/site-packages/aiohttp/connector.py", line 571, in _create_connection
    server_hostname=hinfo['hostname'] if sslcontext else None)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 669, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 687, in _create_connection_transport
    server_side=False, server_hostname=server_hostname)
  File "/tmp/python/lib/python3.5/site-packages/aiouv/_events.py", line 394, in _make_ssl_transport
    return selector_events._SelectorSslTransport(self, rawsock, protocol, sslcontext, waiter, server_side, server_hostname, extra, server)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 782, in __init__
    logger.debug("%r starts SSL handshake", self)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
```

How to reproduce:

```
#!/usr/bin/env python3.5
import logging
import os
import warnings

import aiohttp
import aiouv


os.environ['PYTHONASYNCIODEBUG'] = '1'
logging.basicConfig(level=logging.DEBUG)
warnings.resetwarnings()


async def fetch(url, loop):
    r = await aiohttp.get(url, loop=loop)
    r.close()

loop = aiouv.EventLoop()
try:
    loop.run_until_complete(fetch('https://api.github.com/events', loop=loop))
finally:
    loop.close()

print("Stopped!")
```

It possible either `EventLoop` shold be compatible with `SelectorEventLoop` (#11) or `EventLoop` shouldn't use any `_Selector*Transport` directly because they expect `SelectorEventLoop`.

**Comment by saghul** [comment]
I'm going to close this in favor of #11, we should inherit from SelectorEventLoop. Patches are welcome, of course :-)
