### ISSUE TITLE
Is EventLoopPolicy using the wrong base class?

### ISSUE THREAD

**Issue by funkybob** [saghul/aiouv#16]
Using the following:

```
asyncio.set_event_loop_policy(aiouv.EventLoopPolicy)
loop = asyncio.get_event_loop()
```

I get the following error:

```
Traceback (most recent call last):
  File "app.py", line 140, in <module>
    asyncio.set_event_loop_policy(aiouv.EventLoopPolicy)
  File "/usr/lib/python3.5/asyncio/events.py", line 620, in set_event_loop_policy
    assert policy is None or isinstance(policy, AbstractEventLoopPolicy)
AssertionError
```

Python 3.5.1+ (debian)
aiouv from git

**Comment by saghul** [comment]
We haven't update aiouv in a while, sadly, so it's possible some things need adjusting. If you feel like going for it feel free to send a pull request! :-)
